#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Globais
int nMotorSpeedSetting = 40;
int direction=0;
int lineColour = -1;
int black = 30;

//Funcoes
void followLine();
void scanLine();
void corrigeErro();
int check(int, int);


void giraDireita(){
	motor[leftwheel] = 10;
	motor[rightwheel] = -10;
}
void giraEsquerda(){
	motor[leftwheel] = -10;
	motor[rightwheel] = 10;
}
int check( int time){
	time1[T1] = 0;
	while(	time1[T1] < time ){
		gira();
		if(SensorValue[colour] < black){
			brake();
			return 1;
		}
	}
	return 0;
}
void brake(){
	motor[leftwheel] = 0;
	motor[rightwheel] = 0;
}

void gira(){
	if(direction == 0){
		direction = 1
	 	giraDireita();
	 } else {
	 	direction = 0;
	 	giraEsquerda();
	 }
}

void corrigeErro(){
	brake();
	int temp = 10;
	int varrer = 0;
	while (true){
		varrer = check(temp);
		if(varrer == 1 || temp >= 100){
			break;
		}
		temp += temp;
	}
	scanLine();
}

void scanLine(){
	while(true)
	{
		if(SensorValue[colour] < black){
			lineColour = SensorValue[colour];
  			break;
  		} else {
	  		if(direction == 0){
	  			giraDireita();
	    		}else{
	    			giraEsquerda();
  			}
  		}
	}
	brake();
  	if (lineColour != -1){
  		followLine();
  	}
}

void followLine(){
	if(direction == 0){
		direction = 1;
	}else{
		direction = 0;
	}
	motor[leftwheel] = nMotorSpeedSetting;
    	motor[rightwheel] = nMotorSpeedSetting;
    	while(SensorValue[colour] < black){
      		sleep(200);
    	}
    	corrigeErro();
}

task main(){
	scanLine();
}
