#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nMotorSpeedSetting = 40;




int direction=0;
int lineColour = -1;
void followLine();
void scanLine();
void corrigeErro();
int black = 45;

void giraDireita(){
	motor[leftwheel] = 10;
	motor[rightwheel] = -10;
}
void giraEsquerda(){
	motor[leftwheel] = -10;
	motor[rightwheel] = 10;
}
void brake(){
motor[leftwheel] = 0;
motor[rightwheel] = 0;
}

void gira(){
 if(direction == 0){
 	direction = 1
 	giraDireita();
 } else {
  direction = 0;
  giraEsquerda();
 }
}

void corrigeErro(){
	time1[T1] = 0;
	brake();
		 while(	time1[T1] < 100 ){
		    gira();
	      if(SensorValue[colour] < black){
	      	brake();
	      	break;
	      }
		 }

		 while(	time1[T1] < 300 ){
		    gira();
	      if(SensorValue[colour] < black){
	      	brake();
	      	break;
	      }
		 }

		 scanLine();
}
void scanLine()
{
  while(true)
  {
  	if(SensorValue[colour] < black){
  		lineColour = SensorValue[colour];
  		break;
  	} else {
	  	if(direction == 0){
	  	  giraDireita();
	    }else{
	    	giraEsquerda();
	  	}
  	}
  }

   brake();
  if (lineColour != -1){
  	followLine();
  }
}

void followLine(){
		if(direction == 0){
			direction = 1;
		}else{
			direction = 0;
		}
		motor[leftwheel] = nMotorSpeedSetting;
    motor[rightwheel] = nMotorSpeedSetting;
    while(SensorValue[colour] < black){
      sleep(200);
    }
    corrigeErro();

}

task main()
{
  scanLine();
}
