#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Sensor, S4,     sonar4,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Globais
int nMotorSpeedSetting = 30;
int direction=0;
int black = 45;
int sleepTime = 200;
int tentativa = 100;
int sleepCorrige = 1000;
int tmaximo = 1500;
const int safeDistance = 30;
int currentDistance = 0;
///////////////


void verificaDistancia();
void giraDireita(){
	motor[leftwheel] = 15;
	motor[rightwheel] = -15;
}
void giraEsquerda(){
	motor[leftwheel] = -15;
	motor[rightwheel] = 15;
}
void re(){
	motor[leftwheel] = -10;
	motor[rightwheel] = -10;
}
void brake(){
	motor[leftwheel] = 0;
	motor[rightwheel] = 0;
}
void celera(){
	
	motor[leftwheel] = 40;
  motor[rightwheel] = 40;
}

void gira(){
	if(direction == 0){
		direction = 1;
	 	giraDireita();
	 } else {
	 	direction = 0;
	 	giraEsquerda();
	 }
}

void corrige(){
	time1[T1] = 0;
	while( time1[T1] < sleepCorrige){
		if(SensorValue[colour] < black){
			brake();
		}	else {
			verificaDistancia();
		}
	}
	
	brake();
}

int yProcura(int time){
	displayCenteredBigTextLine(4, "Procurando Linha");
	time1[T1] = 0;
	gira();

	while( time1[T1] < time){		
		if(SensorValue[colour] < black){
			brake();
			return 1;
		}
	}
	brake();
	return 0;
}

void verificaDistancia(){
	currentDistance = SensorValue[sonar4];
	//displayCenteredBigTextLine(4, "Dist: %3d cm", currentDistance);
	// So vai lek
  if ((safeDistance - currentDistance) < -2)
		{
			celera();
		}
		// Muito Perto
		else if ((safeDistance - currentDistance) > 2)
		{
			while((safeDistance - currentDistance) > 2){	
				currentDistance = SensorValue[sonar4];
				displayCenteredBigTextLine(4, "Fuuu");
				re();		
				
			}
			brake();
		}
		// We're good, don't go anywhere
		else
		{
			while((safeDistance - currentDistance) >= 2){	
				currentDistance = SensorValue[sonar4];
				displayCenteredBigTextLine(4, "stand by");
				brake();	
				sleep(200);
			}
		}
}

void yScanLine();
void followLine(){
	  displayCenteredBigTextLine(4, "Na Linha");
    while(SensorValue[colour] < black){
    	displayCenteredBigTextLine(4, "Na Linha2");
    	verificaDistancia();
    	sleep(sleepTime);
    }
    yScanLine();
}

void yScanLine(){
	tentativa = 100;
	displayCenteredBigTextLine(4, "Scan");
	while(yProcura(tentativa) == 0){	
	brake();
		sleep(200);
		if(tentativa > tmaximo){
			// Corrige indo pouquin pra frente
			corrige();

			tentativa = 100;
		} else {
			tentativa = tentativa + 200;
		}		
	}
	followLine();
}

task main(){
	displayCenteredBigTextLine(4, "Ola Mundo");
	while(yProcura(2000) == 0){
		corrige();		
	}

	followLine();
}
