#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Globais
int nMotorSpeedSetting = 30;
int direction=0;
int lineColour = -1;
int black = 45;
int sleepTime = 200;
int tentativa = 100;
int sleepCorrige = 300;
int tmaximo = 1000;
///////////////

void giraDireita(){
	motor[leftwheel] = 10;
	motor[rightwheel] = -10;
}
void giraEsquerda(){
	motor[leftwheel] = -10;
	motor[rightwheel] = 10;
}
void brake(){
	motor[leftwheel] = 0;
	motor[rightwheel] = 0;
}
void celera(){
	motor[leftwheel] = nMotorSpeedSetting;
    motor[rightwheel] = nMotorSpeedSetting;
}

void gira(){
	if(direction == 0){
		direction = 1;
	 	giraDireita();
	 } else {
	 	direction = 0;
	 	giraEsquerda();
	 }
}

int yProcura(int time){
	time1[T1] = 0;
	gira();

	while( time1[T1] < time){		
		if(SensorValue[colour] < black){
			brake();
			return 1;
		}
	}
	brake();
	return 0;
}

void yScanLine();
void followLine(){	
	celera();
    while(SensorValue[colour] < black){
    	sleep(sleepTime);
    }
    yScanLine();
}

void yScanLine(){
	tentativa = 100;
	while(yProcura(tentativa) == 0){	

		if(tentativa > tmaximo){
			// Corrige indo pouquin pra frente
			celera();
			sleep(sleepCorrige);

			tentativa = 100;
		} else {
			tentativa = tentativa + 200;
		}		
	}
	followLine();
}

task main(){
	yScanLine();
}